### ISSUE TITLE
Build failure when streaming is disabled

### ISSUE THREAD

**Issue by MatthiasWauer** [rauc/rauc#2018]
**Describe the bug**
Link stage fails if streaming is disabled.

**Background information**
master @ 98adedba6e3ddb47155e332b1042b68496679f5c

Introduced in 7f5a37b83965a496133639bc8b2f8c15589410d1

**To Reproduce**
```
meson setup -Dgpt=enabled -Djson=enabled -Dnetwork=false -Dservice=true -Dstreaming=false --prefix=/usr build && ninja -C build
...
/usr/bin/ld: librauc.a.p/src_polling.c.o: in function `polling_fetch':
..build/../src/polling.c:113:(.text.polling_fetch+0x123): undefined reference to `r_nbd_error_quark'
/usr/bin/ld: ..build/../src/polling.c:118:(.text.polling_fetch+0x183): undefined reference to `r_nbd_error_quark'
```

**Expected behavior**
Build succeeds

**Logs**

**Additional context**
