### PR TITLE
src/polling: fix build if streaming is disabled

### LINKED ISSUE #2018: Build failure when streaming is disabled
**Describe the bug**
Link stage fails if streaming is disabled.

**Background information**
master @ 98adedba6e3ddb47155e332b1042b68496679f5c

Introduced in 7f5a37b83965a496133639bc8b2f8c15589410d1

**To Reproduce**
```
meson setup -Dgpt=enabled -Djson=enabled -Dnetwork=false -Dservice=true -Dstreaming=false --prefix=/usr build && ninja -C build
...
/usr/bin/ld: librauc.a.p/src_polling.c.o: in function `polling_fetch':
..build/../src/polling.c:113:(.text.polling_fetch+0x123): undefined reference to `r_nbd_error_quark'
/usr/bin/ld: ..build/../src/polling.c:118:(.text.polling_fetch+0x183): undefined reference to `r_nbd_error_quark'
```

**Expected behavior**
Build succeeds

**Logs**

**Additional context**

### PR DESCRIPTION
**Pull request by MatthiasWauer**
In case steaming is disabled the NBD errors are not defined,  leading to a linker failure

```c
// ndb.h
#define R_NBD_ERROR r_nbd_error_quark()
//ndb.c
r_nbd_error_quark(void) {...}
```

Fix it by including the checks for NDB errors only when streaming is enabled.

Fixes: #2018

### CODE REVIEW

**Comment by ejoerns** [comment]
I'm not sure if we should compile `polling.c` at all if streaming is disabled, since polling doesn't work without streaming.

However, if we disable the module, this would require some changes to `src/service.c` which calls `r_polling_setup()`, etc.

@jluebbe Do you have a preferred solution?

**Comment by jluebbe** [comment]
Polling without streaming is not useful. We should be able to have stubs in `include/polling.h`.

Because `src/config.h` accesses `r_polling_supported_install_criteria` (and others), parts of `parse_polling_section()` need to be made compile-time conditional, too.

We should also add a CI build without network or streaming to CI, but that should be a different PR.
